const Actions = {
    SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
    HANDLE_SEARCH: 'HANDLE_SEARCH',
    HANDLE_FILTER: 'HANDLE_FILTER',
    EMPTY_PRODUCT_LIST: 'EMPTY_PRODUCT_LIST'
}

export default Actions;